### ISSUE TITLE
The contents from the ".../vendor/magento/quality-patches/patches.json" file can't be read.

### ISSUE THREAD

**Issue by ProxiBlue** [elgentos/magento2-composer-quality-patches#4]
I think something may have changed in the magento quality patches module, as the given patches.json file no longer exists, and looks like they split the patches to two source JSON files:

community-patches.json
support-patches.json

**Comment by my-brain-qlicks** [comment]
this one will do the compatibility constraint
https://github.com/elgentos/magento2-composer-quality-patches/pull/5

Compatibility with the most recent version of quality patches would require a full-on refactoring

**Comment by ProxiBlue** [comment]
Hello,

Although this will make this package continue to function, would this not lock the patches to be stale?
As far as I can see (https://github.com/magento/quality-patches/tree/1.0.26/patches) the patches are included in the quality-patches module releases, so, being locked down to that will in effect just keep on old patches.

So, essentially cause a false positive that 'all available patches are handled', and very likely just fail with 'no patches' due to magento versions not handled. 

Someone may not notice. It may be prudent to make a mention in the README about the version constraint to alert persons it may no longer have up to date patches

Unless they pull in updates dynamically? which I did not check, but seems unlikely as the patches are IN the repo itself.

**Comment by my-brain-qlicks** [comment]
@ProxiBlue sure. But this constraint would represent the current state of this package and additionally makes it usable. At least for the outdated quality patches.

This fact it worth mentioning in repository's readme, but that is up to the maintainer.

**Comment by peterjaap** [comment]
I'll revisit this when I have the time to take a thorough deep dive into this again.

**Comment by peterjaap** [comment]
Fixed during the HyväCamp Hackathon! :partying_face:
